import style from './style.module.css';

interface Props {
    active?: boolean;
}

export default function TrainingAnimation({ active }: Props) {
    return (
        <svg viewBox="0 0 100 65">
            <g className={style.lines}>
                <line
                    x2={30}
                    y2={10}
                    x1={10}
                    y1={10}
                />
                <line
                    x2={30}
                    y2={25}
                    x1={10}
                    y1={25}
                />
                <line
                    x2={30}
                    y2={40}
                    x1={10}
                    y1={40}
                />
                <line
                    x2={30}
                    y2={55}
                    x1={10}
                    y1={55}
                />
                <line
                    x1={30}
                    y1={10}
                    x2={50}
                    y2={17.5}
                />
                <line
                    x1={30}
                    y1={10}
                    x2={50}
                    y2={32.5}
                />
                <line
                    x1={30}
                    y1={10}
                    x2={50}
                    y2={47.5}
                />
                <line
                    x1={30}
                    y1={25}
                    x2={50}
                    y2={17.5}
                />
                <line
                    x1={30}
                    y1={25}
                    x2={50}
                    y2={32.5}
                />
                <line
                    x1={30}
                    y1={25}
                    x2={50}
                    y2={47.5}
                />
                <line
                    x1={30}
                    y1={40}
                    x2={50}
                    y2={17.5}
                />
                <line
                    x1={30}
                    y1={40}
                    x2={50}
                    y2={32.5}
                />
                <line
                    x1={30}
                    y1={40}
                    x2={50}
                    y2={47.5}
                />
                <line
                    x1={30}
                    y1={55}
                    x2={50}
                    y2={17.5}
                />
                <line
                    x1={30}
                    y1={55}
                    x2={50}
                    y2={32.5}
                />
                <line
                    x1={30}
                    y1={55}
                    x2={50}
                    y2={47.5}
                />
                <line
                    x2={70}
                    y2={17.5}
                    x1={50}
                    y1={17.5}
                />
                <line
                    x2={70}
                    y2={32.5}
                    x1={50}
                    y1={32.5}
                />
                <line
                    x2={70}
                    y2={47.5}
                    x1={50}
                    y1={47.5}
                />
                <line
                    x2={70}
                    y2={32.5}
                    x1={50}
                    y1={17.5}
                />
                <line
                    x2={70}
                    y2={47.5}
                    x1={50}
                    y1={32.5}
                />
                <line
                    x2={70}
                    y2={17.5}
                    x1={50}
                    y1={47.5}
                />
                <line
                    x2={70}
                    y2={47.5}
                    x1={50}
                    y1={17.5}
                />
                <line
                    x2={70}
                    y2={17.5}
                    x1={50}
                    y1={32.5}
                />
                <line
                    x2={70}
                    y2={32.5}
                    x1={50}
                    y1={47.5}
                />

                <line
                    x1={70}
                    y1={47.5}
                    x2={90}
                    y2={47.5}
                />
                <line
                    x1={70}
                    y1={17.5}
                    x2={90}
                    y2={17.5}
                />
                <line
                    x1={70}
                    y1={32.5}
                    x2={90}
                    y2={32.5}
                />
            </g>
            <g className={active ? style.layersActive : style.layers}>
                <g className={style.layer1}>
                    <circle
                        cx={30}
                        cy={10}
                        r={5}
                    />
                    <circle
                        cx={30}
                        cy={25}
                        r={5}
                    />
                    <circle
                        cx={30}
                        cy={40}
                        r={5}
                    />
                    <circle
                        cx={30}
                        cy={55}
                        r={5}
                    />
                </g>

                <g className={style.layer2}>
                    <circle
                        cx={50}
                        cy={17.5}
                        r={5}
                    />
                    <circle
                        cx={50}
                        cy={32.5}
                        r={5}
                    />
                    <circle
                        cx={50}
                        cy={47.5}
                        r={5}
                    />
                </g>
                <g className={style.layer3}>
                    <circle
                        cx={70}
                        cy={17.5}
                        r={5}
                    />
                    <circle
                        cx={70}
                        cy={32.5}
                        r={5}
                    />
                    <circle
                        cx={70}
                        cy={47.5}
                        r={5}
                    />
                </g>
            </g>
        </svg>
    );
}
